language: php

php:
  - 5.3

before_script:
  - ./protected/tests/travis/apache-setup.sh
  - ./protected/tests/travis/mysql-setup.sh
  - ./protected/tests/travis/app-setup.sh
  - ./protected/tests/travis/phpunit-selenium-setup.sh
  - ./protected/tests/travis/selenium-setup.sh
  - cd protected/tests

script: phpunit --colors --coverage-text ./
