language: php

php:
  - 5.3

before_script:
  - chmod -R 0777 ./assets
  - chmod -R 0777 ./protected/runtime
  - ./protected/tests/travis/apache-setup.sh
  - ./protected/tests/travis/mysql-setup.sh
  - ./protected/tests/travis/phpunit-selenium-setup.sh
  - wget -O /tmp/selenium-server-standalone.jar http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
  - java -jar /tmp/selenium-server-standalone.jar &
  - export DISPLAY=:99.0
  - sudo sh -e /etc/init.d/xvfb start
  - sleep 3
  - cd protected/tests

script: phpunit --colors --coverage-text ./
