language: php

php:
  - 5.3

before_script:
  - chmod -R 0777 ./assets
  - chmod -R 0777 ./images
  - chmod -R 0777 ./protected/runtime
  - ./protected/tests/travis/apache-setup.sh
  - ./protected/tests/travis/mysql-setup.sh
  - dpkg -l | grep php5
  - ./protected/tests/travis/php-setup.sh
  - ./protected/tests/travis/phpunit-selenium-setup.sh
  - firefox --version
  - wget -O /tmp/test.uwc2012.delfit.loc_requirements.html http://test.uwc2012.delfit.loc/lib/yii-1.1.12/requirements/index.php
  - cat /tmp/test.uwc2012.delfit.loc_requirements.html
  - wget -O /tmp/test.uwc2012.delfit.loc_index.html http://test.uwc2012.delfit.loc 
  - cat /tmp/test.uwc2012.delfit.loc_index.html
  - wget -O /tmp/selenium-server-standalone.jar http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
  - java -jar /tmp/selenium-server-standalone.jar &
  - export DISPLAY=:99.0
  - sudo sh -e /etc/init.d/xvfb start
  - sleep 3
  - cd protected/tests

script: phpunit --colors --coverage-text ./
